name: Portfolio CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run a one-line script
      run: echo "Checking your portfolio files..."

    - name: List files in the repository
      run: ls -R